React UI - POC
BlueJayADAL/JayRadar pull request #21
Opened 2023-08-06 18:26 UTC by ethanlaj

This will split the files between api and client, making it easier for development.

Python app correctly serves the built index.html file in the client/dist directory. React components are displayed correctly

2023-08-06 21:10 UTC, Klinefelters commented on api/interfaces/react_ui.py
Docstrings and comments need to be added. Either in this PR, or open an issue to look over all docstrings and comments.

2023-08-06 21:11 UTC, Klinefelters commented on api/models/frc7ng480.pt
The models folder needs to be reviewed. This should also probably be a new issue.

2023-08-06 21:14 UTC, Klinefelters commented
In general, the following needs to be done before this PR can be merged with main:

1. Install, run and dev-run scripts should be added, or a new issue for this should be made
2. Comments on current code should be resolved, mostly about new issues and such
3. The frontend has a bug where when switching tabs it resets the sliders. This should be fixed

2023-08-06 21:22 UTC, Klinefelters commented on api/models/frc7ng480.pt
Made a new issue

2023-08-06 21:37 UTC, ethanlaj commented on api/interfaces/react_ui.py
This should be added in this PR. We shouldn't make a habit of opening new issues for problems created by updating the code

2023-08-06 22:56 UTC, Klinefelters requested changes
Final changes...

Since this change adds dependencies it needs to be tested and installation instructions on the wiki need to be updated after release.

2023-08-07 00:02 UTC, ethanlaj commented on api/interfaces/react_ui.py
Added comments

2023-08-07 00:18 UTC, ethanlaj commented
@Klinefelters Trello ticket created to create those scripts

https://trello.com/c/3lgjTQ8L/16-add-scripts-to-root-directory

2023-08-07 01:24 UTC, Klinefelters approved these changes

2023-08-07 01:50 UTC, merged